#!/bin/sh

echo 'Running pre-push checks ...'
docker-compose exec -T client bin/parallel-lint --exclude vendor .
docker-compose exec -T client bin/phpcs src/ tests/ --standard=PSR2,PSR12
docker-compose exec -T client bin/phpstan analyse -l max src/ tests/
docker-compose exec -T client bin/phpunit
