version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout

      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist
      - run: cp .env.example .env

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run: ./bin/parallel-lint --exclude vendor .
      - run: ./bin/phpcs src/ tests/ --standard=PSR2,PSR12 --report=summary -p
      - run: ./bin/phpstan analyse -l max src/ tests/
      - run: ./bin/phpunit --log-junit ./reports/phpunit.xml --coverage-xml reports/coverage
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output
